[workspace]
resolver = "2"
members = [
    "crates/xteink-ui",
    "crates/xteink-scenario-harness",
    "crates/xteink-sim-web",
    "crates/xteink-sim-desktop",
    "crates/xteink-firmware",
]

[workspace.dependencies]
epublet = { path = "../epublet", default-features = false }

[profile.release]
opt-level = "s"
lto = true
