[workspace]
resolver = "2"
members = [
    "crates/xteink-ui",
    "crates/xteink-sim-web",
    "crates/xteink-sim-desktop",
    "crates/xteink-firmware", "crates/ssd1677",
]

[profile.release]
opt-level = "s"
lto = true
