[workspace]
resolver = "2"
members = [
    "crates/xteink-ui",
    "crates/xteink-scenario-harness",
    "crates/xteink-sim-web",
    "crates/xteink-sim-desktop",
    "crates/xteink-firmware",
]

[workspace.dependencies]
epublet = { path = "../epublet", default-features = false }
epublet-render = { path = "../epublet/crates/epublet-render" }
epublet-embedded-graphics = { path = "../epublet/crates/epublet-embedded-graphics" }

[profile.release]
opt-level = "s"
lto = true
